[project]
name = "convertor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.2.1",
    "pyinstaller>=6.13.0",
    "pystray>=0.19.5",
    "wmi>=1.5.1",
]
